from datetime import datetime
from enum import Enum
from typing import Optional, Any
from pydantic import BaseModel, Field


class CommandType(str, Enum):
    withdraw_consent = "withdraw_consent"
    analyze_offer = "analyze_offer"


class CommandPayload(BaseModel):
    user_id: str = Field(..., example="user-123")
    payload: dict = Field(default_factory=dict)


class CommandRequest(BaseModel):
    command: CommandType
    data: CommandPayload
    requested_at: datetime = Field(default_factory=datetime.utcnow)


class CommandResponse(BaseModel):
    command_id: str
    status: str = "accepted"


# Bot event schemas for Kafka
class BotEventType(str, Enum):
    message = "message"
    callback_query = "callback_query"
    command = "command"


class BotEvent(BaseModel):
    """Event from bot-core to hr-bot"""
    event_id: str
    event_type: BotEventType
    company_id: int
    chat_id: int
    user_id: int
    username: Optional[str] = None
    message_text: Optional[str] = None
    callback_data: Optional[str] = None
    command: Optional[str] = None
    document_id: Optional[str] = None
    photo_id: Optional[str] = None
    document_content: Optional[bytes] = None  # File content downloaded by bot-core
    document_filename: Optional[str] = None  # Original filename
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    metadata: dict = Field(default_factory=dict)


class BotResponseType(str, Enum):
    text_message = "text_message"
    document = "document"
    photo = "photo"
    edit_message = "edit_message"
    answer_callback = "answer_callback"
    delete_message = "delete_message"


class BotResponse(BaseModel):
    """Response from hr-bot to bot-core"""
    response_id: str
    event_id: str  # Reference to original event
    response_type: BotResponseType
    company_id: int
    chat_id: int
    text: Optional[str] = None
    document_path: Optional[str] = None
    document_content: Optional[bytes] = None  # File content for documents generated by hr-bot
    document_filename: Optional[str] = None  # Filename for document_content
    photo_path: Optional[str] = None
    callback_query_id: Optional[str] = None
    callback_text: Optional[str] = None
    edit_message_id: Optional[int] = None
    delete_message_id: Optional[int] = None
    reply_markup: Optional[dict] = None
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    metadata: dict = Field(default_factory=dict)

